[package]
name = "mikino_api"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@ocamlpro.com>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "mikino"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
force-color = []

[dependencies]
ansi_term = "^0.12"
atty = "^0.2"
clap = "^2.33"
error-chain = "^0.12"
num = "^0.4"
rsmt2 = "^0.12"